[package]
name = "enhansed_music_player"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = { version = "0.21.0", features = ["symphonia-all"] }
clap = { version = "4.0", features = ["derive"] }
mp3-duration = "0.1.10"
